export const mockStuff = {
	companions: [
		{ id: 1, name: 'Sausage', slug: 'sausage', rarity: 'uncommon', base_mp: 1, types: ['small', 'food'] },
		{ id: 2, name: 'Sunny', slug: 'sunny', rarity: 'uncommon', base_mp: 1, types: ['small', 'food'] },
		{ id: 3, name: 'Bread', slug: 'bread', rarity: 'uncommon', base_mp: 1, types: ['small', 'food'] },
		{ id: 4, name: 'Cracker', slug: 'cracker', rarity: 'uncommon', base_mp: 2, types: ['food', 'dessert', 'small'] },
		{ id: 5, name: 'Pudding', slug: 'pudding', rarity: 'uncommon', base_mp: 2, types: ['food', 'dessert', 'small'] },
		{ id: 6, name: 'Cake', slug: 'cake', rarity: 'uncommon', base_mp: 2, types: ['food', 'dessert', 'small'] },
		{ id: 7, name: 'Tamago', slug: 'tamago', rarity: 'rare', base_mp: 3, types: ['small', 'food'] },
		{ id: 8, name: 'Carrot', slug: 'carrot', rarity: 'rare', base_mp: 3, types: ['small', 'plant'] },
		{ id: 9, name: 'Clover', slug: 'clover', rarity: 'rare', base_mp: 3, types: ['small', 'plant'] },
		{ id: 10, name: 'Trunk', slug: 'trunk', rarity: 'rare', base_mp: 3, types: ['small', 'plant'] },
		{ id: 11, name: 'Takoyaki', slug: 'takoyaki', rarity: 'rare', base_mp: 3, types: ['small', 'food'] },
		{ id: 12, name: 'Chick', slug: 'chick', rarity: 'rare', base_mp: 3, types: ['animal', 'chicken', 'small'] },
		{ id: 13, name: 'Burger', slug: 'burger', rarity: 'rare', base_mp: 3, types: ['food', 'hamburger', 'small'] },
		{ id: 14, name: 'Jackdolf', slug: 'jackdolf', rarity: 'epic', base_mp: 4, types: ['animal', 'pirate', 'wolf', 'small'] },
		{ id: 15, name: 'Mouse', slug: 'mouse', rarity: 'epic', base_mp: 4, types: ['small', 'machine'] },
		{ id: 16, name: 'Pingu', slug: 'pingu', rarity: 'epic', base_mp: 4, types: ['small', 'animal'] },
		{ id: 17, name: 'Ghost Cat', slug: 'ghost-cat', rarity: 'epic', base_mp: 4, types: ['animal', 'cat', 'small'] },
		{ id: 18, name: 'Bunny', slug: 'bunny', rarity: 'epic', base_mp: 4, types: ['animal', 'magic', 'small'] },
		{ id: 19, name: 'Fire Chick', slug: 'fire-chick', rarity: 'epic', base_mp: 4, types: ['animal', 'chicken', 'small'] },
		{ id: 20, name: 'Tulip', slug: 'tulip', rarity: 'epic', base_mp: 4, types: ['small', 'plant'] },
		{ id: 21, name: 'Phoenix', slug: 'phoenix', rarity: 'epic', base_mp: 4, types: ['animal', 'chicken', 'small'] },
		{ id: 22, name: 'Lightree', slug: 'lightree', rarity: 'epic', base_mp: 4, types: ['small', 'plant'] },
		{ id: 23, name: 'Whopper', slug: 'whopper', rarity: 'epic', base_mp: 4, types: ['food', 'hamburger', 'small'] },
		{ id: 24, name: 'Drake', slug: 'drake', rarity: 'epic', base_mp: 4, types: ['animal', 'dragon', 'small'] },
		{ id: 25, name: 'Spark', slug: 'spark', rarity: 'epic', base_mp: 4, types: ['animal', 'dragon', 'small'] },
		{ id: 26, name: 'Cookie Knight', slug: 'cookie-knight', rarity: 'epic', base_mp: 4, types: ['food', 'dessert', 'magic', 'small'] },
		{ id: 27, name: 'Pumpky', slug: 'pumpky', rarity: 'epic', base_mp: 4, types: ['plant', 'magic', 'small'] },
		{ id: 28, name: 'Steel Fin', slug: 'steel-fin', rarity: 'epic', base_mp: 4, types: ['machine', 'pirate', 'shark', 'small'] },
		{ id: 29, name: 'Angry Bomb', slug: 'angry-bomb', rarity: 'epic', base_mp: 4, types: ['small', 'machine'] },
		{ id: 30, name: 'Devil Cat', slug: 'devil-cat', rarity: 'epic', base_mp: 4, types: ['animal', 'cat', 'small'] },
		{ id: 31, name: 'Bro', slug: 'bro', rarity: 'epic', base_mp: 4, types: ['animal', 'cat', 'small'] },
		{ id: 32, name: 'Sparrow', slug: 'sparrow', rarity: 'epic', base_mp: 4, types: ['small', 'animal'] },
		{ id: 33, name: 'Cat Black', slug: 'cat-black', rarity: 'legendary', base_mp: 6, types: ['machine', 'cat', 'medium'] },
		{ id: 34, name: 'Jack Striker', slug: 'jack-striker', rarity: 'legendary', base_mp: 8, types: ['animal', 'pirate', 'shark', 'large'] },
		{ id: 35, name: 'Werewolf', slug: 'werewolf', rarity: 'legendary', base_mp: 8, types: ['animal', 'wolf', 'large'] },
		{ id: 36, name: 'Grom', slug: 'grom', rarity: 'legendary', base_mp: 8, types: ['animal', 'wolf', 'small'] },
		{ id: 37, name: 'Lulu', slug: 'lulu', rarity: 'legendary', base_mp: 8, types: ['animal', 'cat', 'magic', 'large', 'cloud'] },
		{ id: 38, name: 'Roro', slug: 'roro', rarity: 'legendary', base_mp: 6, types: ['animal', 'cat', 'magic', 'medium', 'cloud'] },
		{ id: 39, name: 'Jack Tiger', slug: 'jack-tiger', rarity: 'legendary', base_mp: 6, types: ['animal', 'pirate', 'cat', 'medium'] },
		{ id: 40, name: 'Jack Jaws', slug: 'jack-jaws', rarity: 'legendary', base_mp: 6, types: ['machine', 'pirate', 'shark', 'medium'] },
		{ id: 41, name: 'Jack Fly', slug: 'jack-fly', rarity: 'legendary', base_mp: 6, types: ['pirate', 'magic', 'dragon', 'medium'] },
		{ id: 42, name: 'War Wolf', slug: 'war-wolf', rarity: 'legendary', base_mp: 6, types: ['machine', 'wolf', 'medium'] },
		{ id: 43, name: 'Jackdaw', slug: 'jackdaw', rarity: 'legendary', base_mp: 8, types: ['animal', 'pirate', 'large'] },
		{ id: 44, name: 'Tanker', slug: 'tanker', rarity: 'legendary', base_mp: 8, types: ['machine', 'cat', 'large'] },
		{ id: 45, name: 'Oracle', slug: 'oracle', rarity: 'mythic', base_mp: 12, types: ['animal', 'cat', 'magic', 'large', 'cloud'] },
		{ id: 46, name: 'Captain Specter', slug: 'captain-specter', rarity: 'mythic', base_mp: 12, types: ['large', 'pirate'] },
	],
	skills: [
		{ id: 1, name: 'Dinner Time', slug: 'dinner-time', rarity: 'common', description: 'Summons 8 food missiles that deal value1% of ATK.', cooldown: 20, types: ['food'] },
		{ id: 2, name: 'Rat Bomb', slug: 'rat-bomb', rarity: 'common', description: 'Summons a rat bomb that explodes soon dealing AoE DMG of 85% of ATK.', cooldown: 13, types: ['machine'] },
		{ id: 3, name: 'Super Cat', slug: 'super-cat', rarity: 'common', description: 'Flies a super cat dealing 178% of ATK.', cooldown: 13, types: ['cat'] },
		{ id: 4, name: 'Magic Circus', slug: 'magic-circus', rarity: 'common', description: 'Throws a ball 2 times a second for 4s that deals 53% of ATK.', cooldown: 13, types: ['magic'] },
		{ id: 5, name: 'Dessert Coma', slug: 'dessert-coma', rarity: 'uncommon', description: 'Drops 5 desserts dealing 45% of ATK on every enemy hit.', cooldown: 20, types: ['food', 'dessert'] },
		{ id: 6, name: 'Leaf Slash', slug: 'leaf-slash', rarity: 'uncommon', description: 'Deals AoE DMG of 14% of ATK on a straight line.', cooldown: 10, types: ['plant'] },
		{ id: 7, name: 'Icy Thorns', slug: 'icy-thorns', rarity: 'uncommon', description: 'Summons a spinning snowflake scattering icy thorns that deal 18% of ATK.', cooldown: 20, types: ['magic'] },
		{ id: 8, name: 'Scratch', slug: 'scratch', rarity: 'uncommon', description: 'Scratches the surface dealing 32% of ATK for 12 times.', cooldown: 13, types: ['cat', 'dragon'] },
		{ id: 9, name: 'Grrrrrr', slug: 'grrrrrr', rarity: 'uncommon', description: 'Increases ASPD by 40% for 5s. Grrrrrr! effect stacks.', cooldown: 30, types: ['wolf'] },
		{ id: 10, name: 'Cluster Bomb', slug: 'cluster-bomb', rarity: 'uncommon', description: 'Shoots a cluster bomb dealing AoE DMG of 107% of ATK.', cooldown: 13, types: ['machine', 'pirate', 'shark'] },
		{ id: 11, name: 'Fish Rain', slug: 'fish-rain', rarity: 'rare', description: 'Summons 12 fish missiles that deal 60% of ATK.', cooldown: 20, types: ['animal'] },
		{ id: 12, name: 'Scarecrow', slug: 'scarecrow', rarity: 'rare', description: 'Summons a scarecrow dealing AoE DMG of 7% of ATK each second for 3s and adds a terror effect to increase DMG to enemies by 50% for 2s.', cooldown: 38, types: [] },
		{ id: 13, name: 'Tornado', slug: 'tornado', rarity: 'rare', description: 'Forms a tornado for 5s that deals AoE DMG of 13% of ATK 4 times a second.', cooldown: 25, types: ['magic'] },
		{ id: 14, name: 'Magic Shield', slug: 'magic-shield', rarity: 'rare', description: 'Decreases received DMG by 30% for 13s.', cooldown: 25, types: ['magic'] },
		{ id: 15, name: 'Chicken Run', slug: 'chicken-run', rarity: 'rare', description: 'Summons 3 chickens that explode soon dealing AoE DMG of 79% of ATK.', cooldown: 20, types: ['machine', 'chicken'] },
		{ id: 16, name: 'Chakra', slug: 'chakra', rarity: 'rare', description: 'Deals AoE DMG of 45% of ATK and drags the enemies to the center.', cooldown: 20, types: ['magic'] },
		{ id: 17, name: 'Howl', slug: 'howl', rarity: 'epic', description: 'Increases Skill DMG by 300% for 5s.', cooldown: 30, types: ['wolf'] },
		{ id: 18, name: 'Black Cloud', slug: 'black-cloud', rarity: 'epic', description: 'Summons a black cloud for 3s and blasts a Penetrating Bolt dealing 200% of ATK upon tapping the screen to attack.', cooldown: 15, types: ['magic', 'cloud'] },
		{ id: 19, name: 'Spray Ink', slug: 'spray-ink', rarity: 'epic', description: "Summons Pirate Octopus and sprays ink to deal 1000% AoE DMG and blind enemies, decreasing the targets' ATK by 40% for 8s.", cooldown: 24, types: ['pirate'] },
		{ id: 20, name: 'Burger Party', slug: 'burger-party', rarity: 'epic', description: 'Throws burger ingredients 2 times a second for 4s that deals 350% of ATK.', cooldown: 38, types: ['food', 'hamburger'] },
		{ id: 21, name: 'Magic Crossbow', slug: 'magic-crossbow', rarity: 'epic', description: 'Summons a magic crossbow for 5s that shoots a penetrating arrow 5 times a second dealing 240% of ATK.', cooldown: 60, types: ['magic'] },
		{ id: 22, name: 'Full Moon', slug: 'full-moon', rarity: 'epic', description: 'Enlarges the cat hero for 5s, throwing extra 6 moon fish with basic attack that deal 80% of ATK.', cooldown: 60, types: ['wolf', 'magic'] },
		{ id: 23, name: 'Catteor', slug: 'catteor', rarity: 'epic', description: 'Drops 15 Cat meteors dealing 600% of ATK on every enemy hit.', cooldown: 50, types: ['cat', 'magic'] },
		{ id: 24, name: 'Cat Laser', slug: 'cat-laser', rarity: 'epic', description: 'Summons a robot cat that beams laser out for 10s dealing AoE DMG of 400% of ATK 3 times a second.', cooldown: 60, types: ['machine', 'cat'] },
		{ id: 25, name: 'Claw Punch', slug: 'claw-punch', rarity: 'legendary', description: 'Scratches the enemy with wolf claws dealing 1500% damage for 2 times.', cooldown: 13, types: ['wolf'] },
		{ id: 26, name: 'Pirate Sign', slug: 'pirate-sign', rarity: 'legendary', description: 'Summons Pirate Cat and leaves a Pirate Sign on all enemies. The sign bursts and deals 300% extra DMG when enemies with the sign attack with a Cat or Pirate type skill.', cooldown: 18.75, types: ['pirate', 'cat'] },
		{ id: 27, name: 'Nocturne Summon', slug: 'nocturne-summon', rarity: 'legendary', description: 'Summons Nocturne dealing AoE DMG of 3000% of ATK and adds a Terror effect to increase DMG received by the targets by 50% for 5s.', cooldown: 75, types: ['pirate', 'dragon'] },
		{ id: 28, name: 'Black Hole', slug: 'black-hole', rarity: 'legendary', description: 'Creates a black hole for 5s that drags the enemies to the front and deals AoE DMG of 300% of ATK 2 times a second.', cooldown: 15, types: ['magic'] },
		{ id: 29, name: 'Dreadnought Whale', slug: 'dreadnought-whale', rarity: 'legendary', description: 'Summons a dreadnought whale that moves forward dealing AoE DMG of 1200% of ATK 3 times a second.', cooldown: 75, types: ['machine', 'pirate'] },
		{ id: 30, name: 'Bombshell Rain', slug: 'bombshell-rain', rarity: 'mythic', description: 'Pours down several bombshells from the sky. The skill lasts for 20s showering 5 bombshells per second. Each bombshell deals 60000% DMG to the enemy.', cooldown: 100, types: ['machine'] },
		{ id: 31, name: 'Shaman Cat', slug: 'shaman-cat', rarity: 'mythic', description: 'Summons a shaman cat. The shaman cat summons 3 clouds that strike red lightning. The clouds last for 10s, dealing DMG of 4 times the second. The red lightning deals 200% of DMG at an area at first attack, and the DMG increases by 200% every attack.', cooldown: 100, types: ['cat', 'magic', 'cloud'] },
		{ id: 32, name: 'Cat Heroes', slug: 'cat-heroes', rarity: 'mythic', description: 'Opens a door in the sky for 10s, and uses an enhanced skill additionally upon casting a Cat type skill of legendary grade and under. The enhanced skill deals extra DMG of 2000% of the original skill DMG.', cooldown: 100, types: ['cat', 'magic', 'cloud'] },
		{ id: 33, name: "Ocean's Punishment", slug: 'oceans-punishment', rarity: 'mythic', description: 'Leaves a Shark Sign on all enemies. The sign stores the DMG received by the target. Deals 3000% of ATK after the sign, and then additionally deals 1500% DMG stored in the sign.', cooldown: 40, types: ['pirate', 'shark'] },
	],
	mainRunes: [
		{ id: 1, name: 'Leaf Slash Enhanced', slug: 'leaf-slash-enhanced', rarity: 'uncommon', description: 'Enhances Leaf Slash increasing Skill DMG by 50 % and area of effect.' },
		{ id: 2, name: 'Magic Circus Enhanced', slug: 'magic-circus-enhanced', rarity: 'uncommon', description: 'Enhances Magic Circus to increase the shoot speed per second by 100 %.' },
		{ id: 3, name: 'Random Uncommon Skill', slug: 'random-uncommon-skill', rarity: 'uncommon', description: 'Casts Uncommon skill that is equipped in the skill slot every 15 seconds.' },
		{ id: 4, name: 'Rat Bomb Enhanced', slug: 'rat-bomb-enhanced', rarity: 'uncommon', description: 'Enhances Rat Bomb to expand the explosion range while increasing Skill DMG by 50 %.' },
		{ id: 5, name: 'Cluster Bomb Enhanced', slug: 'cluster-bomb-enhanced', rarity: 'uncommon', description: 'Enhances Cluster Bomb to expand the explosion range while increasing Skill DMG by 50 %.' },
		{ id: 6, name: 'Scraaatch Enhanced', slug: 'scraaatch-enhanced', rarity: 'uncommon', description: 'Enhances Scraaatch to kill the target immediately when its HP is lower than 10%.' },
		{ id: 7, name: 'Grrrrrrr! Enhanced', slug: 'grrrrrrr-enhanced', rarity: 'uncommon', description: 'Enhances Grrrrrrr! to increase the duration by 5 seconds.' },
		{ id: 8, name: 'Dessert Coma Enhanced', slug: 'dessert-coma-enhanced', rarity: 'uncommon', description: 'Enhances Dessert Coma increasing Skill DMG by 50%.' },
		{ id: 9, name: 'Dinner Time Enhanced', slug: 'dinner-time-enhanced', rarity: 'uncommon', description: 'Enhances Dinner Time increasing Skill DMG by 50%.' },
		{ id: 10, name: 'Icy Thorns Enhanced', slug: 'icy-thorns-enhanced', rarity: 'uncommon', description: 'Enhances Icy Thorns to shoot 2 orbs.' },
		{ id: 11, name: 'Super Cat Enhanced-II', slug: 'super-cat-enhanced-ii', rarity: 'uncommon', description: 'Enhances Super Cat to bounce 1 times.' },
		{ id: 12, name: 'Black Cloud Enhanced', slug: 'black-cloud-enhanced', rarity: 'rare', description: 'Summons extra 1 Black Cloud upon casting Black Cloud.' },
		{ id: 13, name: 'Magic Shield Enhanced', slug: 'magic-shield-enhanced', rarity: 'rare', description: 'Enhances Magic Shield to become immune to attacks by 30% chance.' },
		{ id: 14, name: 'Tornado Enhanced', slug: 'tornado-enhanced', rarity: 'rare', description: 'Enhances Tornado to increase DMG by 100%.' },
		{ id: 15, name: 'Cluster Bomb Enhanced', slug: 'cluster-bomb-enhanced', rarity: 'rare', description: 'Enhances Cluster Bomb to expand the explosion range while increasing Skill DMG by 150%.' },
		{ id: 16, name: 'Chakra Enhanced', slug: 'chakra-enhanced', rarity: 'rare', description: 'Enhances Chakra to give an electric shock to the hit target by 20% chance increasing received DMG by 30% for 5 seconds.' },
		{ id: 17, name: 'Dinner Time Enhanced', slug: 'dinner-time-enhanced', rarity: 'rare', description: 'Enhances Dinner Time to summon extra 8 food missiles dealing 150% damage of Skill DMG.' },
		{ id: 18, name: 'Chicken Run Enhanced', slug: 'chicken-run-enhanced', rarity: 'rare', description: 'Enhances Chicken Run to summon extra 3 while increasing Skill DMG by 70%.' },
		{ id: 19, name: 'Random Rare Skill', slug: 'random-rare-skill', rarity: 'rare', description: 'Casts Rare skill that is equipped in the skill slot every 15 seconds.' },
		{ id: 20, name: 'Super Cat Enhanced-II', slug: 'super-cat-enhanced-ii', rarity: 'rare', description: 'Enhances Super Cat to bounce 2 times.' },
		{ id: 21, name: 'Rat Bomb Enhanced', slug: 'rat-bomb-enhanced', rarity: 'rare', description: 'Enhances Rat Bomb to summon extra 3 while increasing Skill DMG by 100%.' },
		{ id: 22, name: 'Super Cat Enhanced-I', slug: 'super-cat-enhanced-i', rarity: 'rare', description: 'Enhances Super Cat to summon extra 3 while increasing Skill DMG by 70%.' },
		{ id: 23, name: 'Fish Rain Enhanced', slug: 'fish-rain-enhanced', rarity: 'rare', description: 'Enhances Fish Rain to shoot extra 8 red fish dealing 150% of Skill DMG.' },
		{ id: 24, name: 'Scarecrow Enhanced', slug: 'scarecrow-enhanced', rarity: 'rare', description: 'Enhances Scarecrow to explode at the end of the skill duration dealing 20% of Max HP of enemies in the area. (N/A for Boss)' },
		{ id: 25, name: 'Dessert Coma Enhanced', slug: 'dessert-coma-enhanced', rarity: 'rare', description: 'Enhances Dessert Coma to summon extra cookies dealing 500% damage of Skill DMG.' },
		{ id: 26, name: 'Random Epic Skill', slug: 'random-epic-skill', rarity: 'epic', description: 'Casts Epic skill that is equipped in the skill slot every 15 seconds.' },
		{ id: 27, name: 'Full Moon Enhanced', slug: 'full-moon-enhanced', rarity: 'epic', description: 'Enhances Full Moon to increase the enlargement duration by 5 seconds.' },
		{ id: 28, name: 'Catteor Enhanced', slug: 'catteor-enhanced', rarity: 'epic', description: 'Enhances Catteor to drop an extra huge meteorite dealing 1,000% of Skill DMG.' },
		{ id: 29, name: 'Black Cloud Enhanced', slug: 'black-cloud-enhanced', rarity: 'epic', description: 'Enhances Black Cloud increasing Skill DMG by 300% and the skill duration by 5 seconds.' },
		{ id: 30, name: 'Howl Enhanced', slug: 'howl-enhanced', rarity: 'epic', description: 'Enhances Howl to increase the duration by 5 seconds.' },
		{ id: 31, name: 'Cat Laser Enhanced', slug: 'cat-laser-enhanced', rarity: 'epic', description: 'Enhances Cat Laser increasing Skill DMG by 500%.' },
		{ id: 32, name: 'Magic Crossbow Enhanced', slug: 'magic-crossbow-enhanced', rarity: 'epic', description: 'Enhances Magic Crossbow to increase DMG by 500%.' },
		{ id: 33, name: 'Burger Party Enhanced', slug: 'burger-party-enhanced', rarity: 'epic', description: 'Enhances Burger Party to shoot an electronic patty by 10% chance. A target hit by the electronic patty receives an electric shock with received DMG increased by 30% for 5 seconds.' },
		{ id: 34, name: 'Random Legendary Skill', slug: 'random-legendary-skill', rarity: 'legendary', description: 'Casts Legendary skill that is equipped in the skill slot every 15 seconds.' },
		{ id: 35, name: 'Claw Punch Enhanced', slug: 'claw-punch-enhanced', rarity: 'legendary', description: 'Enhances Claw Punch to deal wide AoE DMG and increase Skill DMG by 1,000%.' },
		{ id: 36, name: 'Shaman Cat Enhanced', slug: 'shaman-cat-enhanced', rarity: 'legendary', description: 'Summons 2 times as many red clouds, increasing hit speed by 2 times.' },
		{ id: 37, name: 'Bombshell Rain Enhanced', slug: 'bombshell-rain-enhanced', rarity: 'legendary', description: 'Increases the number of bombshells of Bombshell Rain by 5 and increase Skill DMG by 1,000%.' },
		{ id: 38, name: 'Cloud Enhanced', slug: 'cloud-enhanced', rarity: 'legendary', description: 'Increases the duration of Cloud type skills by 5s and the Skill DMG of Cloud type skill by 1,000%.' },
		{ id: 39, name: 'Black Hole Enhanced', slug: 'black-hole-enhanced', rarity: 'legendary', description: 'Enhances Black Hole to create an electric shock wave upon casting the skill. The electric shock wave deals 2,000% of ATK and gives an electric shock increasing the received DMG by 500% for 5 seconds.' },
		{ id: 40, name: 'Dreadnought Whale Enhanced', slug: 'dreadnought-whale-enhanced', rarity: 'legendary', description: 'Enhances Dreadnought Whale to fire missiles to the front in succession. A missile deals 1,000% of the Skill DMG.' },
		{ id: 41, name: 'Pirate x2', slug: 'pirate-x2', rarity: 'legendary', description: 'Activates one more time at a 30% chance when casting a Pirate type skill. Skill DMG of a recurrent Skill increases by 500%.' },
		{ id: 42, name: 'Summon Cat Laser', slug: 'summon-cat-laser', rarity: 'legendary', description: 'Casts a bonus Cat Laser by a 30 % chance upon casting a Cat type skill. Increases the CRIT DMG of the bonus Cat Laser by 500 %.' },
		{ id: 43, name: 'Cat Electric Shock', slug: 'cat-electric-shock', rarity: 'legendary', description: 'Gives an electric shock by 10 % chance upon hitting an enemy with Cat type skills increasing DMG received by the target by 500 % for 5 seconds.' },
		{ id: 44, name: 'Shaman Cat Enhanced 2', slug: 'shaman-cat-enhanced-2', rarity: 'mythic', description: 'Increases the extra DMG of Shaman Cat by 5,000 %.' },
		{ id: 45, name: 'Cat Heroes Enhanced', slug: 'cat-heroes-enhanced', rarity: 'mythic', description: 'Enhances Cat Heroes to increase extra DMG by 5,000 %.' },
		{ id: 46, name: 'Guardian Angel', slug: 'guardian-angel', rarity: 'mythic', description: 'Resurrects upon death. Increases final DMG by 5,000 % for 5s after the resurrection.' },
		{ id: 47, name: "Ocean's Punishment Enhanced", slug: 'oceans-punishment-enhanced', rarity: 'mythic', description: 'Reduces the DMG dealt by the target with a Shark Sign by 50 %. Increases DMG dealt to the target with a Shark Sign by 5,000 %.' },
		{ id: 48, name: 'Bombshell Rain Enhanced 2', slug: 'bombshell-rain-enhanced-2', rarity: 'mythic', description: 'Increases the extra DMG of Bombshell Rain by 5,000 %.' },
	],
	subRunes: [
		{ id: 1, name: 'Dragon Enhanced', slug: 'dragon-enhanced', rarity: 'uncommon', description: 'Increases DMG of all skills by 10% per one Dragon companion equipped.', type__name: null, values: [] },
		{ id: 2, name: 'Small Enhanced', slug: 'small-enhanced', rarity: 'uncommon', description: 'Increases DMG of all skills by 10% per one Small companion equipped.', type__name: null, values: [] },
		{ id: 3, name: 'Shark Enhanced', slug: 'shark-enhanced', rarity: 'uncommon', description: 'Increases the Skill DMG of Shark type skills by 20% per one Shark companion equipped.', type__name: null, values: [] },
		{ id: 4, name: 'CRIT Chance', slug: 'crit-chance', rarity: 'uncommon', description: 'Increases CRIT Chance by 10%.', type__name: null, values: [] },
		{ id: 5, name: 'Wolf Enhanced', slug: 'wolf-enhanced', rarity: 'uncommon', description: 'Increases the Skill DMG of Wolf type skills by 20% per one Wolf companion equipped.', type__name: null, values: [] },
		{ id: 6, name: 'ATK', slug: 'atk', rarity: 'uncommon', description: 'ATK Boost + 50%', type__name: null, values: [] },
		{ id: 7, name: 'Medium Enhanced', slug: 'medium-enhanced', rarity: 'uncommon', description: 'Increases DMG of all skills by 10% per one Medium companion equipped.', type__name: null, values: [] },
		{ id: 8, name: 'Dessert Enhanced', slug: 'dessert-enhanced', rarity: 'uncommon', description: 'Increases the Skill DMG of Dessert type skills by 20% per one Dessert companion equipped.', type__name: null, values: [] },
		{ id: 9, name: 'Fish Boost', slug: 'fish-boost', rarity: 'uncommon', description: 'Fish DMG Boost + 25%', type__name: null, values: [] },
		{ id: 10, name: 'Cloud Enhanced', slug: 'cloud-enhanced', rarity: 'uncommon', description: 'Increases DMG of all skills by 10% per one Cloud companion equipped.', type__name: null, values: [] },
		{ id: 11, name: 'Boss Attack', slug: 'boss-attack', rarity: 'uncommon', description: 'Boss DMG Increase + 10%', type__name: null, values: [] },
		{ id: 12, name: 'Chicken Enhanced', slug: 'chicken-enhanced', rarity: 'uncommon', description: 'Increases DMG of all skills by 10% per one Chicken companion equipped.', type__name: null, values: [] },
		{ id: 13, name: 'Animal Enhanced', slug: 'animal-enhanced', rarity: 'uncommon', description: 'Increases All DMG by 3% per one Animal companion equipped.', type__name: null, values: [] },
		{ id: 14, name: 'Cat Enhanced', slug: 'cat-enhanced', rarity: 'uncommon', description: 'Increases the Skill DMG of Cat type skills by 20% per one Cat companion equipped.', type__name: null, values: [] },
		{ id: 15, name: 'Machine Enhanced', slug: 'machine-enhanced', rarity: 'uncommon', description: 'Increases the Skill DMG of Machine type skills by 20% per one Machine companion equipped.', type__name: null, values: [] },
		{ id: 16, name: 'CRIT DMG', slug: 'crit-dmg', rarity: 'uncommon', description: 'CRIT DMG Boost + 25%', type__name: null, values: [] },
		{ id: 17, name: 'Triple Shot', slug: 'triple-shot', rarity: 'uncommon', description: 'Increases Triple Shot by 5%.', type__name: null, values: [] },
		{ id: 18, name: 'Large Enhanced', slug: 'large-enhanced', rarity: 'uncommon', description: 'Increases DMG of all skills by 10% per one Large companion equipped.', type__name: null, values: [] },
		{ id: 19, name: 'Magic Enhanced', slug: 'magic-enhanced', rarity: 'uncommon', description: 'Increases the Skill DMG of Magic type skills by 20% per one Magic companion equipped.', type__name: null, values: [] },
		{ id: 20, name: 'Double Shot', slug: 'double-shot', rarity: 'uncommon', description: 'Increases Double Shot by 10%.', type__name: null, values: [] },
		{ id: 21, name: 'Hamburger Enhanced', slug: 'hamburger-enhanced', rarity: 'uncommon', description: 'Increases DMG of all skills by 10% per one Hamburger companion equipped.', type__name: null, values: [] },
		{ id: 22, name: 'Food Enhanced', slug: 'food-enhanced', rarity: 'uncommon', description: 'Increases the Skill DMG of Food type skills by 20% per one Food companion equipped.', type__name: null, values: [] },
		{ id: 23, name: 'Plant Enhanced', slug: 'plant-enhanced', rarity: 'uncommon', description: 'Increases the Skill DMG of Plant type skills by 20% per one Plant companion equipped.', type__name: null, values: [] },
		{ id: 24, name: 'Plant Enhanced', slug: 'plant-enhanced', rarity: 'rare', description: 'Increases the Skill DMG of Plant type skills by 40% per one Plant companion equipped.', type__name: null, values: [] },
		{ id: 25, name: 'Triple Shot', slug: 'triple-shot', rarity: 'rare', description: 'Increases Triple Shot by 10%.', type__name: null, values: [] },
		{ id: 26, name: 'Fish Boost', slug: 'fish-boost', rarity: 'rare', description: 'Fish DMG Boost + 50%', type__name: null, values: [] },
		{ id: 27, name: 'Boss Attack', slug: 'boss-attack', rarity: 'rare', description: 'Boss DMG Increase + 20%', type__name: null, values: [] },
		{ id: 28, name: 'Chicken Enhanced', slug: 'chicken-enhanced', rarity: 'rare', description: 'Increases DMG of all skills by 20% per one Chicken companion equipped.', type__name: null, values: [] },
		{ id: 29, name: 'Cat Enhanced', slug: 'cat-enhanced', rarity: 'rare', description: 'Increases the Skill DMG of Cat type skills by 40% per one Cat companion equipped.', type__name: null, values: [] },
		{ id: 30, name: 'Animal Enhanced', slug: 'animal-enhanced', rarity: 'rare', description: 'Increases All DMG by 5% per one Animal companion equipped.', type__name: null, values: [] },
		{ id: 31, name: 'Machine Enhanced', slug: 'machine-enhanced', rarity: 'rare', description: 'Increases the Skill DMG of Machine type skills by 40% per one Machine companion equipped.', type__name: null, values: [] },
		{ id: 32, name: 'Plant MP Improved', slug: 'plant-mp-improved', rarity: 'rare', description: 'Reduces required MP for Plant of Rare grade by 1.', type__name: 'reduce_mp_for_companion_type_and_rarity', values: ['1', 'plant', 'rare'] },
		{ id: 33, name: 'Dragon Enhanced', slug: 'dragon-enhanced', rarity: 'rare', description: 'Increases DMG of all skills by 20% per one Dragon companion equipped.', type__name: null, values: [] },
		{ id: 34, name: 'CRIT DMG', slug: 'crit-dmg', rarity: 'rare', description: 'CRIT DMG Boost + 50%', type__name: null, values: [] },
		{ id: 35, name: 'Small Enhanced', slug: 'small-enhanced', rarity: 'rare', description: 'Increases DMG of all skills by 20% per one Small companion equipped.', type__name: null, values: [] },
		{ id: 36, name: 'Cloud Enhanced', slug: 'cloud-enhanced', rarity: 'rare', description: 'Increases DMG of all skills by 20% per one Cloud companion equipped.', type__name: null, values: [] },
		{ id: 37, name: 'Dessert Enhanced', slug: 'dessert-enhanced', rarity: 'rare', description: 'Increases the Skill DMG of Dessert type skills by 40% per one Dessert companion equipped.', type__name: null, values: [] },
		{ id: 38, name: 'ATK', slug: 'atk', rarity: 'rare', description: 'ATK Boost + 100%', type__name: null, values: [] },
		{ id: 39, name: 'Shark Enhanced', slug: 'shark-enhanced', rarity: 'rare', description: 'Increases the Skill DMG of Shark type skills by 40% per one Shark companion equipped.', type__name: null, values: [] },
		{ id: 40, name: 'Double Shot', slug: 'double-shot', rarity: 'rare', description: 'Increases Double Shot by 20%.', type__name: null, values: [] },
		{ id: 41, name: 'Wolf Enhanced', slug: 'wolf-enhanced', rarity: 'rare', description: 'Increases the Skill DMG of Wolf type skills by 40% per one Wolf companion equipped.', type__name: null, values: [] },
		{ id: 42, name: 'CRIT Chance', slug: 'crit-chance', rarity: 'rare', description: 'Increases CRIT Chance by 20%.', type__name: null, values: [] },
		{ id: 43, name: 'Hamburger Enhanced', slug: 'hamburger-enhanced', rarity: 'rare', description: 'Increases DMG of all skills by 20% per one Hamburger companion equipped.', type__name: null, values: [] },
		{ id: 44, name: 'Magic Enhanced', slug: 'magic-enhanced', rarity: 'rare', description: 'Increases the Skill DMG of Magic type skills by 40% per one Magic companion equipped.', type__name: null, values: [] },
		{ id: 45, name: 'Large Enhanced', slug: 'large-enhanced', rarity: 'rare', description: 'Increases DMG of all skills by 20% per one Large companion equipped.', type__name: null, values: [] },
		{ id: 46, name: 'Medium Enhanced', slug: 'medium-enhanced', rarity: 'rare', description: 'Increases DMG of all skills by 20% per one Medium companion equipped.', type__name: null, values: [] },
		{ id: 47, name: 'Food Enhanced', slug: 'food-enhanced', rarity: 'rare', description: 'Increases the Skill DMG of Food type skills by 40% per one Food companion equipped.', type__name: null, values: [] },
		{ id: 48, name: 'Boss Attack', slug: 'boss-attack', rarity: 'epic', description: 'Boss DMG Increase + 40%.', type__name: null, values: [] },
		{ id: 49, name: 'ATK', slug: 'atk', rarity: 'epic', description: 'ATK Boost + 200%.', type__name: null, values: [] },
		{ id: 50, name: 'Animal Enhanced', slug: 'animal-enhanced', rarity: 'epic', description: 'Increases All DMG by 10% per one Animal companion equipped.', type__name: null, values: [] },
		{ id: 51, name: 'Dragon Enhanced', slug: 'dragon-enhanced', rarity: 'epic', description: 'Increases DMG of all skills by 40% per one Dragon companion equipped.', type__name: null, values: [] },
		{ id: 52, name: 'Fish Boost', slug: 'fish-boost', rarity: 'epic', description: 'Fish DMG Boost + 100%.', type__name: null, values: [] },
		{ id: 53, name: 'Plant MP Improved', slug: 'plant-mp-improved', rarity: 'epic', description: 'Reduces required MP for Plant of Epic grade by 1.', type__name: 'reduce_mp_for_companion_type_and_rarity', values: ['1', 'plant', 'epic'] },
		{ id: 54, name: 'Triple Shot', slug: 'triple-shot', rarity: 'epic', description: 'Increases Triple Shot by 20%.', type__name: null, values: [] },
		{ id: 55, name: 'Animal MP Improved', slug: 'animal-mp-improved', rarity: 'epic', description: 'Reduces required MP for Animal of Epic grade by 1.', type__name: 'reduce_mp_for_companion_type_and_rarity', values: ['1', 'animal', 'epic'] },
		{ id: 56, name: 'Machine Enhanced', slug: 'machine-enhanced', rarity: 'epic', description: 'Increases the Skill DMG of Machine type skills by 80% per one Machine companion equipped.', type__name: null, values: [] },
		{ id: 57, name: 'CRIT DMG', slug: 'crit-dmg', rarity: 'epic', description: 'CRIT DMG Boost + 100%.', type__name: null, values: [] },
		{ id: 58, name: 'Cat Enhanced', slug: 'cat-enhanced', rarity: 'epic', description: 'Increases the Skill DMG of Cat type skills by 80% per one Cat companion equipped.', type__name: null, values: [] },
		{ id: 59, name: 'Machine MP Improved', slug: 'machine-mp-improved', rarity: 'epic', description: 'Reduces required MP for Machine of Epic grade by 1.', type__name: 'reduce_mp_for_companion_type_and_rarity', values: ['1', 'machine', 'epic'] },
		{ id: 60, name: 'Magic Enhanced', slug: 'magic-enhanced', rarity: 'epic', description: 'Increases the Skill DMG of Magic type skills by 80% per one Magic companion equipped.', type__name: null, values: [] },
		{ id: 61, name: 'Dessert Enhanced', slug: 'dessert-enhanced', rarity: 'epic', description: 'Increases the Skill DMG of Dessert type skills by 80% per one Dessert companion equipped.', type__name: null, values: [] },
		{ id: 62, name: 'Wolf Enhanced', slug: 'wolf-enhanced', rarity: 'epic', description: 'Increases the Skill DMG of Wolf type skills by 80% per one Wolf companion equipped.', type__name: null, values: [] },
		{ id: 63, name: 'Small Enhanced', slug: 'small-enhanced', rarity: 'epic', description: 'Increases DMG of all skills by 40% per one Small companion equipped.', type__name: null, values: [] },
		{ id: 64, name: 'Shark Enhanced', slug: 'shark-enhanced', rarity: 'epic', description: 'Increases the Skill DMG of Shark type skills by 80% per one Shark companion equipped.', type__name: null, values: [] },
		{ id: 65, name: 'Cloud Enhanced', slug: 'cloud-enhanced', rarity: 'epic', description: 'Increases DMG of all skills by 40% per one Cloud companion equipped.', type__name: null, values: [] },
		{ id: 66, name: 'Hamburger Enhanced', slug: 'hamburger-enhanced', rarity: 'epic', description: 'Increases DMG of all skills by 40% per one Hamburger companion equipped.', type__name: null, values: [] },
		{ id: 67, name: 'Large Enhanced', slug: 'large-enhanced', rarity: 'epic', description: 'Increases DMG of all skills by 40% per one Large companion equipped.', type__name: null, values: [] },
		{ id: 68, name: 'Food Enhanced', slug: 'food-enhanced', rarity: 'epic', description: 'Increases the Skill DMG of Food type skills by 80% per one Food companion equipped.', type__name: null, values: [] },
		{ id: 69, name: 'Medium Enhanced', slug: 'medium-enhanced', rarity: 'epic', description: 'Increases DMG of all skills by 40% per one Medium companion equipped.', type__name: null, values: [] },
		{ id: 70, name: 'Cloud Enhanced 2', slug: 'cloud-enhanced-2', rarity: 'epic', description: 'Increases the Skill DMG of Cloud type skills by 80% per one Cloud companion equipped.', type__name: null, values: [] },
		{ id: 71, name: 'Plant Enhanced', slug: 'plant-enhanced', rarity: 'epic', description: 'Increases the Skill DMG of Plant type skills by 80% per one Plant companion equipped.', type__name: null, values: [] },
		{ id: 72, name: 'Chicken Enhanced', slug: 'chicken-enhanced', rarity: 'epic', description: 'Increases DMG of all skills by 40% per one Chicken companion equipped.', type__name: null, values: [] },
		{ id: 73, name: 'Animal Enhanced', slug: 'animal-enhanced', rarity: 'legendary', description: 'Increases All DMG by 30% per one Animal companion equipped.', type__name: null, values: [] },
		{ id: 74, name: 'Machine Enhanced', slug: 'machine-enhanced', rarity: 'legendary', description: 'Increases the Skill DMG of Machine type skills by 160% per one Machine companion equipped.', type__name: null, values: [] },
		{ id: 75, name: 'Hamburger Enhanced', slug: 'hamburger-enhanced', rarity: 'legendary', description: 'Increases DMG of all skills by 80% per one Hamburger companion equipped.', type__name: null, values: [] },
		{ id: 76, name: 'Zero MP Hamburger', slug: 'zero-mp-hamburger', rarity: 'legendary', description: "Nullifies Hamburger companion's MP.", type__name: 'reduce_mp_for_companion_type_and_rarity', values: ['1000', 'burger', 'all'] },
		{ id: 77, name: 'Cloud Enhanced', slug: 'cloud-enhanced', rarity: 'legendary', description: 'Increases DMG of all skills by 80% per one Cloud companion equipped.', type__name: null, values: [] },
		{ id: 78, name: 'Legendary Enhancement', slug: 'legendary-enhancement', rarity: 'legendary', description: 'Increases the Skill DMG of Legendary skills by 200% per one Legendary companion equipped.', type__name: null, values: [] },
		{ id: 79, name: 'Shark Enhanced', slug: 'shark-enhanced', rarity: 'legendary', description: 'Increases the Skill DMG of Shark type skills by 160% per one Shark companion equipped.', type__name: null, values: [] },
		{ id: 80, name: 'Wolf MP Improved', slug: 'wolf-mp-improved', rarity: 'legendary', description: 'Reduces required MP for Wolf of Legendary grade by 2.', type__name: 'reduce_mp_for_companion_type_and_rarity', values: ['2', 'wolf', 'legendary'] },
		{ id: 81, name: 'Wolf Enhanced', slug: 'wolf-enhanced', rarity: 'legendary', description: 'Increases the Skill DMG of Wolf type skills by 160% per one Wolf companion equipped.', type__name: null, values: [] },
		{ id: 82, name: 'Wolf Enhanced', slug: 'wolf-enhanced-2', rarity: 'legendary', description: 'Increases DMG of all skills by 80% per one Wolf companion equipped.', type__name: null, values: [] },
		{ id: 83, name: 'Machine MP Improved', slug: 'machine-mp-improved', rarity: 'legendary', description: 'Reduces required MP for Machine of Legendary grade by 2.', type__name: 'reduce_mp_for_companion_type_and_rarity', values: ['2', 'machine', 'legendary'] },
		{ id: 84, name: 'Large Enhanced', slug: 'large-enhanced', rarity: 'legendary', description: 'Increases DMG of all skills by 80% per one Large companion equipped.', type__name: null, values: [] },
		{ id: 85, name: 'Chicken Enhanced', slug: 'chicken-enhanced', rarity: 'legendary', description: 'Increases DMG of all skills by 80% per one Chicken companion equipped.', type__name: null, values: [] },
		{ id: 86, name: 'Medium Enhanced', slug: 'medium-enhanced', rarity: 'legendary', description: 'Increases DMG of all skills by 80% per one Medium companion equipped.', type__name: null, values: [] },
		{ id: 87, name: 'CRIT DMG', slug: 'crit-dmg', rarity: 'legendary', description: 'CRIT DMG Boost + 200%', type__name: null, values: [] },
		{ id: 88, name: 'Cat Skill Boost', slug: 'cat-skill-boost', rarity: 'legendary', description: 'Increases the deal ratio of Cat type skills by 150% per each Cat type skill equipped.', type__name: null, values: [] },
		{ id: 89, name: 'Magic Enhanced', slug: 'magic-enhanced', rarity: 'legendary', description: 'Increases the Skill DMG of Magic type skills by 160% per one Magic companion equipped.', type__name: null, values: [] },
		{ id: 90, name: 'Dragon Enhanced', slug: 'dragon-enhanced', rarity: 'legendary', description: 'Increases DMG of all skills by 80% per one Dragon companion equipped.', type__name: null, values: [] },
		{ id: 91, name: 'Boss Attack', slug: 'boss-attack', rarity: 'legendary', description: 'Boss DMG Increase + 80%', type__name: null, values: [] },
		{ id: 92, name: 'Plant Enhanced', slug: 'plant-enhanced', rarity: 'legendary', description: 'Increases the Skill DMG of Plant type skills by 160% per one Plant companion equipped.', type__name: null, values: [] },
		{ id: 93, name: 'Fish Boost', slug: 'fish-boost', rarity: 'legendary', description: 'Fish DMG Boost + 200%', type__name: null, values: [] },
		{ id: 94, name: 'Small Enhanced', slug: 'small-enhanced', rarity: 'legendary', description: 'Increases DMG of all skills by 80% per one Small companion equipped.', type__name: null, values: [] },
		{ id: 95, name: 'Cat Boost', slug: 'cat-boost', rarity: 'legendary', description: 'Increases final DMG by 200% for 3s after casting a Cat type skill.', type__name: null, values: [] },
		{ id: 96, name: 'Dessert Enhanced', slug: 'dessert-enhanced', rarity: 'legendary', description: 'Increases the Skill DMG of Dessert type skills by 160% per one Dessert companion equipped.', type__name: null, values: [] },
		{ id: 97, name: 'Cat CRIT Boost', slug: 'cat-crit-boost', rarity: 'legendary', description: 'Increases CRIT DMG Boost by 150% with each equipped Cat companion.', type__name: null, values: [] },
		{ id: 98, name: 'Pirate Boost', slug: 'pirate-boost', rarity: 'legendary', description: 'Increases final DMG by 200% for 3s after casting a Pirate type skill.', type__name: null, values: [] },
		{ id: 99, name: 'Pirate Skill Boost', slug: 'pirate-skill-boost', rarity: 'legendary', description: 'Increases the deal ratio of Pirate type skills by 200% per each Pirate type skill equipped.', type__name: null, values: [] },
		{ id: 100, name: 'Pirate CRIT Boost', slug: 'pirate-crit-boost', rarity: 'legendary', description: 'Increases CRIT DMG Boost by 150% with each equipped Pirate companion.', type__name: null, values: [] },
		{ id: 101, name: 'Pirate CRIT Enhanced', slug: 'pirate-crit-enhanced', rarity: 'legendary', description: 'Increases CRIT DMG dealt by 150% with each equipped Pirate companion.', type__name: null, values: [] },
		{ id: 102, name: 'Animal MP Improved', slug: 'animal-mp-improved', rarity: 'legendary', description: 'Reduces required MP for Animal of Legendary grade by 2.', type__name: 'reduce_mp_for_companion_type_and_rarity', values: ['2', 'animal', 'legendary'] },
		{ id: 103, name: 'Food Enhanced', slug: 'food-enhanced', rarity: 'legendary', description: 'Increases the Skill DMG of Food type skills by 160% per one Food companion equipped.', type__name: null, values: [] },
		{ id: 104, name: 'Cat Enhanced', slug: 'cat-enhanced', rarity: 'legendary', description: 'Increases the Skill DMG of Cat type skills by 160% per one Cat companion equipped.', type__name: null, values: [] },
		{ id: 105, name: 'Max MP Increased', slug: 'max-mp-increased', rarity: 'legendary', description: 'Increases the maximum MP by 4.', type__name: 'increase_max_mp', values: ['4'] },
		{ id: 106, name: 'Pirate CRIT Enhanced', slug: 'pirate-crit-enhanced', rarity: 'mythic', description: 'Increases CRIT DMG dealt by 1,500% with each equipped Pirate companion.', type__name: null, values: [] },
		{ id: 107, name: 'Pirate CRIT Boost', slug: 'pirate-crit-boost', rarity: 'mythic', description: 'Increases CRIT DMG Boost by 1,500% with each equipped Pirate companion.', type__name: null, values: [] },
		{ id: 108, name: 'Pirate Boost', slug: 'pirate-boost', rarity: 'mythic', description: 'Increases final DMG by 5,000% for 3s after casting a Pirate type skill.', type__name: null, values: [] },
		{ id: 109, name: 'Cat CRIT Boost', slug: 'cat-crit-boost', rarity: 'mythic', description: 'Increases CRIT DMG Boost by 1,500% with each equipped Cat companion.', type__name: null, values: [] },
		{ id: 110, name: 'Cat Boost', slug: 'cat-boost', rarity: 'mythic', description: 'Increases final DMG by 5,000% for 3s after casting a Cat type skill.', type__name: null, values: [] },
		{ id: 111, name: 'Wolf CRIT Enhanced', slug: 'wolf-crit-enhanced', rarity: 'mythic', description: 'Increases CRIT DMG dealt by 1,500% with each equipped Wolf companion.', type__name: null, values: [] },
	],
	rarities: ['common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic'],
};

export const getMockData = (type: string) => {
	const data: any = mockStuff;
	if (data !== null) {
		if (data.hasOwnProperty(type)) {
			return data[type];
		}
	}
	return [];
};
